# Generated by Django 5.1.4 on 2026-07-16 18:34

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventario', '0004_fabricante_tipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='codigo_patrimonio',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código patrimonial'),
        ),
        migrations.AddField(
            model_name='componente',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de série'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='status',
            field=models.CharField(choices=[('em_estoque', 'Em estoque'), ('instalado', 'Instalado'), ('removido', 'Removido')], default='em_estoque', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('instalacao', 'Instalação'), ('saida', 'Saída')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='HistoricoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('campo', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(blank=True, max_length=255)),
                ('valor_novo', models.CharField(blank=True, max_length=255)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='inventario.componente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Alteração',
                'verbose_name_plural': 'Histórico de Alterações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='PecaPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('disco_capacidade', models.CharField(blank=True, max_length=10)),
                ('disco_tipo', models.CharField(blank=True, max_length=5)),
                ('disco_interface', models.CharField(blank=True, max_length=5)),
                ('ativo', models.BooleanField(default=True)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_padrao', to='inventario.fabricante')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_padrao', to='inventario.tipocomponente')),
            ],
            options={
                'verbose_name': 'Peça Padrão',
                'verbose_name_plural': 'Peças Padrão',
                'ordering': ['tipo', 'fabricante', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servidores', to='inventario.datacenter')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'ordering': ['hostname'],
                'unique_together': {('hostname', 'data_center')},
            },
        ),
        migrations.AddField(
            model_name='componente',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes', to='inventario.servidor'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.servidor'),
        ),
    ]
