# Generated by Django 5.1.4 on 2026-07-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_componente_codigo_patrimonio_componente_numero_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuário'), ('leitura', 'Viewer')], default='user', max_length=10),
        ),
    ]
