# Generated by Django 5.1.4 on 2026-07-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componente',
            options={'ordering': ['-data_entrada'], 'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
        migrations.AlterModelOptions(
            name='fabricante',
            options={'ordering': ['nome'], 'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='historicoalteracao',
            options={'ordering': ['-data'], 'verbose_name': 'Change History', 'verbose_name_plural': 'Change History'},
        ),
        migrations.AlterModelOptions(
            name='limiteestoque',
            options={'verbose_name': 'Stock Limit', 'verbose_name_plural': 'Stock Limits'},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data'], 'verbose_name': 'Movement', 'verbose_name_plural': 'Movements'},
        ),
        migrations.AlterModelOptions(
            name='pecapadrao',
            options={'ordering': ['tipo', 'fabricante', 'modelo'], 'verbose_name': 'Standard Part', 'verbose_name_plural': 'Standard Parts'},
        ),
        migrations.AlterModelOptions(
            name='servidor',
            options={'ordering': ['hostname'], 'verbose_name': 'Server', 'verbose_name_plural': 'Servers'},
        ),
        migrations.AlterModelOptions(
            name='tipocomponente',
            options={'ordering': ['nome'], 'verbose_name': 'Component Type', 'verbose_name_plural': 'Component Types'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='componente',
            name='codigo_patrimonio',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Asset tag'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='status',
            field=models.CharField(choices=[('em_estoque', 'In stock'), ('instalado', 'Installed'), ('removido', 'Removed')], default='em_estoque', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Added'), ('instalacao', 'Installed'), ('saida', 'Removed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tipocomponente',
            name='categoria',
            field=models.CharField(choices=[('disco', 'Disk'), ('ram', 'RAM Memory'), ('cpu', 'CPU (Processor)'), ('psu', 'Power Supply Unit (PSU)'), ('custom', 'Custom')], default='disco', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Administrator'), ('user', 'User'), ('leitura', 'Viewer')], default='user', max_length=10),
        ),
    ]
