# Generated by Django 5.1.4 on 2026-07-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_componente_options_alter_fabricante_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='ram_capacidade',
            field=models.CharField(blank=True, choices=[('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB')], max_length=10),
        ),
        migrations.AddField(
            model_name='componente',
            name='ram_interface',
            field=models.CharField(blank=True, choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10),
        ),
        migrations.AddField(
            model_name='componente',
            name='ram_tipo',
            field=models.CharField(blank=True, choices=[('UDIMM', 'UDIMM'), ('RDIMM', 'RDIMM')], max_length=10),
        ),
    ]
