# Generated by Django 5.1.4 on 2026-07-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_componente_ram_capacidade_componente_ram_interface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='ram_perfil',
            field=models.CharField(blank=True, choices=[('VLP', 'VLP'), ('LP', 'LP')], max_length=5),
        ),
    ]
